#!/usr/bin/env python3
"""Bake ABVM staff portraits into compact Luau RGB rows.

The output deliberately contains no Roblox asset IDs. Each 48x48 portrait is encoded as
hex RGB rows and rendered at runtime with small horizontal UIGradient strips. This keeps
the approved staff photographs inside the place binary and avoids any dependency on the
Roblox Assets API or EditableImage security toggle.
"""
from __future__ import annotations

import argparse
import hashlib
import io
import pathlib
import subprocess
import sys


WIDTH = 48
HEIGHT = 48
SEGMENT = 16


def read_manifest(path: pathlib.Path):
    rows = []
    seen = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("|", 2)
        if len(parts) != 3:
            raise SystemExit(f"invalid manifest row: {raw}")
        staff_id, display_name, url = (p.strip() for p in parts)
        if not staff_id or staff_id in seen:
            raise SystemExit(f"duplicate/empty staff id: {staff_id!r}")
        seen.add(staff_id)
        rows.append((staff_id, display_name, url))
    if len(rows) != 18:
        raise SystemExit(f"expected 18 faculty/staff rows, got {len(rows)}")
    return rows


def run(*args: str, capture: bool = False) -> bytes:
    proc = subprocess.run(
        list(args),
        check=True,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
    )
    return proc.stdout if capture else b""


def ppm_tokens(blob: bytes):
    i = 0
    n = len(blob)
    while i < n:
        while i < n and blob[i] in b" \t\r\n":
            i += 1
        if i >= n:
            return
        if blob[i] == 35:  # #
            while i < n and blob[i] not in b"\r\n":
                i += 1
            continue
        start = i
        while i < n and blob[i] not in b" \t\r\n#":
            i += 1
        yield blob[start:i]


def parse_ppm(blob: bytes):
    stream = io.BytesIO(blob)

    def token() -> bytes:
        out = bytearray()
        while True:
            ch = stream.read(1)
            if not ch:
                raise ValueError("unexpected EOF in PPM header")
            if ch == b"#":
                stream.readline()
                continue
            if ch not in b" \t\r\n":
                out.extend(ch)
                break
        while True:
            ch = stream.read(1)
            if not ch or ch in b" \t\r\n":
                break
            out.extend(ch)
        return bytes(out)

    magic = token()
    if magic != b"P6":
        raise ValueError(f"expected P6 PPM, got {magic!r}")
    width = int(token())
    height = int(token())
    maxval = int(token())
    if (width, height, maxval) != (WIDTH, HEIGHT, 255):
        raise ValueError(f"unexpected PPM shape {(width, height, maxval)}")
    pixels = stream.read(width * height * 3)
    if len(pixels) != width * height * 3:
        raise ValueError("short PPM pixel payload")
    return pixels


def download(url: str, dest: pathlib.Path):
    run(
        "curl", "-fsSL", "--retry", "3", "--retry-delay", "1",
        "--connect-timeout", "20", "--max-time", "90",
        url, "-o", str(dest),
    )
    if not dest.exists() or dest.stat().st_size < 1024:
        raise SystemExit(f"portrait download too small: {url}")


def convert_to_rgb(src: pathlib.Path) -> bytes:
    # Normalize every source into the same tight, face-forward square. The source set is
    # school-directory portraiture, so a north-weighted central crop preserves hair/face
    # while discarding most torso/background before the 48x48 sampling pass.
    blob = run(
        "convert", str(src),
        "-auto-orient",
        "-resize", "96x96^",
        "-gravity", "North",
        "-extent", "96x96",
        "-crop", "74x74+11+2",
        "+repage",
        "-filter", "Lanczos",
        "-resize", f"{WIDTH}x{HEIGHT}!",
        "-colorspace", "sRGB",
        "-depth", "8",
        "ppm:-",
        capture=True,
    )
    return parse_ppm(blob)


def hex_rows(pixels: bytes):
    rows = []
    stride = WIDTH * 3
    for y in range(HEIGHT):
        row = pixels[y * stride:(y + 1) * stride]
        rows.append(row.hex().upper())
    return rows


def luau_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit(entries, out_path: pathlib.Path):
    lines = [
        "--!strict",
        "-- AUTO-GENERATED by school/neighborhood/tools/bake_faculty_portraits.py",
        "-- Source photographs are the approved Assumption BVM staff references listed in faculty-portrait-sources.tsv.",
        "-- Do not hand-edit this file; regenerate it instead.",
        "local Portraits = {",
        f'    __meta={{generated=true,width={WIDTH},height={HEIGHT},segment={SEGMENT},count={len(entries)}}},',
    ]
    for staff_id, display_name, url, digest, rows in entries:
        lines.append(f"    {staff_id}={{")
        lines.append(f"        name={luau_quote(display_name)},")
        lines.append(f"        source={luau_quote(url)},")
        lines.append(f"        sourceSha256={luau_quote(digest)},")
        lines.append(f"        width={WIDTH},height={HEIGHT},segment={SEGMENT},")
        lines.append("        rows={")
        for row in rows:
            lines.append(f'            "{row}",')
        lines.append("        },")
        lines.append("    },")
    lines += ["}", "", "return Portraits", ""]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--workdir", required=True)
    args = parser.parse_args()

    manifest = pathlib.Path(args.manifest)
    out_path = pathlib.Path(args.out)
    workdir = pathlib.Path(args.workdir)
    workdir.mkdir(parents=True, exist_ok=True)

    entries = []
    for staff_id, display_name, url in read_manifest(manifest):
        src = workdir / f"{staff_id}.source"
        download(url, src)
        pixels = convert_to_rgb(src)
        digest = hashlib.sha256(src.read_bytes()).hexdigest()
        entries.append((staff_id, display_name, url, digest, hex_rows(pixels)))
        print(f"baked {staff_id}: {digest[:12]}", file=sys.stderr)

    emit(entries, out_path)
    text = out_path.read_text(encoding="utf-8")
    if text.count("rows={") != 18:
        raise SystemExit("generated module does not contain 18 portrait payloads")
    print(f"wrote {out_path} with {len(entries)} portraits")


if __name__ == "__main__":
    main()
