local path = "school/src/shared/LegacyOutfitEntry.lua"
local file = assert(io.open(path, "r"))
local text = file:read("*a")
file:close()

local function has(fragment, label)
    if not text:find(fragment, 1, true) then
        error("missing avatar/customization entry contract: " .. (label or fragment), 2)
    end
end

local function lacks(fragment, label)
    if text:find(fragment, 1, true) then
        error("unverified avatar/customization surface leaked: " .. (label or fragment), 2)
    end
end

has('return "OutfitsMobile"', "mobile exact GUI identity")
has('return "OutfitsConsole"', "console exact GUI identity")
has('return "Outfits"', "desktop exact GUI identity")
has('entry.Text = "Custom Outfits"', "exact Custom Outfits label")
has('gui.IgnoreGuiInset = true', "outfit surface uses explicit safe-area ownership")
has('local Rhs2UiStyle = require(ReplicatedStorage:WaitForChild("Shared"):WaitForChild("Rhs2UiStyle"))', "shared RHS2 outfit visual style")
has('Rhs2UiStyle.applyPrimaryPanel(panel)', "outfit panel consumes RHS2 primary chrome")
has('Rhs2UiStyle.applyHeader(title)', "outfit title consumes RHS2 header chrome")
has('Rhs2UiStyle.applyTab(slot, false)', "outfit slots consume RHS2 tab chrome")
has('panel.Name = "OutfitInputs"', "exact OutfitInputs hierarchy")
has('panel.Size = UDim2.fromOffset(286, 400)', "outfit panel base height contains verified content")
has('panel.Position = UDim2.fromOffset(0, 0)', "outfit panel position is responsive-shell owned")
has('panel.ClipsDescendants = true', "outfit content cannot leak outside the responsive panel")
has('panelScale = Instance.new("UIScale")', "responsive outfit panel scale")
has('slots.Name = "OutfitSlots"', "exact OutfitSlots hierarchy")
has('pages.Name = "OutfitPages"', "exact OutfitPages hierarchy")
has('morphs.Name = "MorphsFrame"', "exact MorphsFrame hierarchy")
has('r6Warning.Text = "[Morphs only work with R6]"', "exact R6 warning")
has('{ name = "WearOutfitLabel", text = "Wear Outfit" }', "exact Wear Outfit label")
has('{ name = "SaveOutfitLabel", text = "Save Outfit:" }', "exact Save Outfit label")
has('{ name = "Hat1Label", text = "Hat 1:" }', "exact Hat 1 label")
has('{ name = "Hat2Label", text = "Hat 2:" }', "exact Hat 2 label")
has('{ name = "Hat3Label", text = "Hat 3:" }', "exact Hat 3 label")
has('{ name = "ShirtLabel", text = "Shirt:" }', "exact Shirt label")
has('{ name = "PantsLabel", text = "Pants:" }', "exact Pants label")
has('{ name = "RemoveShirtLabel", text = "Remove Shirt:" }', "exact Remove Shirt label")
has('{ name = "OutfitNameLabel", text = "Outfit Name:" }', "exact Outfit Name label")
has('label:SetAttribute("ReferenceExactLayout", false)', "verified labels do not imply verified layout")
has('slots:SetAttribute("SavedOutfitSlotCount", 12)', "exact saved outfit count")
has('pages:SetAttribute("PageStart1", 1)', "page start 1")
has('pages:SetAttribute("PageStart2", 4)', "page start 4")
has('pages:SetAttribute("PageStart3", 7)', "page start 7")
has('pages:SetAttribute("PageStart4", 10)', "page start 10")
has('gui:SetAttribute("ReferenceExactLayout", false)', "unknown layout remains explicit")
has('panel.Visible = not panel.Visible', "entry open-close behavior")
has('panel = panel,', "mounted panel handle returned to canonical shell")
has('panelScale = panelScale,', "mounted scale handle returned to canonical shell")
lacks('panel.Size = UDim2.fromOffset(286, 262)', "legacy panel too short for verified labels")
lacks('panel.Position = UDim2.new(0.5, -143, 0.5, -131)', "fixed outfit panel position")
lacks("Hat4", "later nine-hat revision must not leak")
lacks("Hat9", "later nine-hat revision must not leak")
lacks("PurchasePermanentItem", "shopping mechanics not guessed before catalog/remote semantics are implemented")

print("HIGH_SCHOOL_AVATAR_CUSTOMIZATION_ENTRY_PASS")
