local path = "school/src/client/CanonicalSchoolClient.client.lua"
local file = assert(io.open(path, "r"))
local source = file:read("*a")
file:close()

local projectFile = assert(io.open("school/default.project.json", "r"))
local project = projectFile:read("*a")
projectFile:close()

local styleFile = assert(io.open("school/src/shared/Rhs2UiStyle.lua", "r"))
local styleSource = styleFile:read("*a")
styleFile:close()

local function has(fragment, label)
    if not source:find(fragment, 1, true) then
        error("missing compact HUD contract: " .. (label or fragment), 2)
    end
end

local function lacks(fragment, label)
    if source:find(fragment, 1, true) then
        error("forbidden compact HUD regression: " .. (label or fragment), 2)
    end
end

local function hasStyle(fragment, label)
    if not styleSource:find(fragment, 1, true) then
        error("missing RHS2 visual style contract: " .. (label or fragment), 2)
    end
end

local function projectHas(fragment, label)
    if not project:find(fragment, 1, true) then
        error("missing RHS2 project mapping: " .. (label or fragment), 2)
    end
end

has('gui.Name = "RobloxHighSchoolLegacyUI"', "stable ScreenGui identity")
has('gui.IgnoreGuiInset = true', "safe-area inset ownership")
has('local ResponsiveHudLayout = require(shared:WaitForChild("ResponsiveHudLayout"))', "shared responsive layout contract")
has('local Rhs2UiStyle = require(shared:WaitForChild("Rhs2UiStyle"))', "shared RHS2 visual style contract")
projectHas('"Rhs2UiStyle"', "Rhs2UiStyle project node")
projectHas('"$path": "src/shared/Rhs2UiStyle.lua"', "Rhs2UiStyle project source")
hasStyle('ShellNavy = Color3.fromRGB(', "dark navy palette family")
hasStyle('HeaderBlue = Color3.fromRGB(', "royal blue palette family")
hasStyle('ActiveGold = Color3.fromRGB(', "gold active-tab family")
hasStyle('ProgressPurple = Color3.fromRGB(', "purple progression family")
hasStyle('Bold = Enum.Font.GothamBold', "Gotham bold typography")
hasStyle('Medium = Enum.Font.GothamMedium', "Gotham medium typography")
hasStyle('Regular = Enum.Font.Gotham', "Gotham regular typography")
has('local FeaturePanelController = require(shared:WaitForChild("FeaturePanelController"))', "single feature-panel controller")
has('card.Name = "CompactSchoolStatus"', "compact school status")
has('card.AnchorPoint = Vector2.new(0, 0)', "geometry contract status anchor")
has('title.Text = "SCHOOL DAY"', "compact status header")
has('actionRail.Name = "RHS2ActionRail"', "right-side action rail")
has('makeRailButton("RailShop", "SHOP"', "shop rail entry")
has('makeRailButton("RailAvatar", "AVATAR"', "avatar rail entry")
has('houseIcon.Parent = actionRail', "house rail entry")
has('makeRailButton("RailTravel", "TRAVEL"', "travel rail entry")
has('Rhs2UiStyle.applyPrimaryRailButton(button, color)', "RHS2 primary rail styling")
has('Rhs2UiStyle.applyPrimaryRailButton(houseIcon, Rhs2UiStyle.Palette.HouseGreen)', "RHS2 House rail styling")
has('quickBar.Name = "RHS2QuickBar"', "bottom quick slots")
has('quickSlot.Name = "QuickSlot" .. tostring(index)', "quick-slot identity")
has('Rhs2UiStyle.applyQuickSlot(quickSlot, slot.color)', "RHS2 quick-slot styling")
has('local function applyResponsiveHudLayout()', "responsive HUD reflow")
has('local camera = Workspace.CurrentCamera', "active viewport source")
has('return GuiService:GetGuiInset()', "device safe-area source")
has('ResponsiveHudLayout.compute(', "responsive geometry computation")
has('ResponsiveHudLayout.validate(layout)', "runtime geometry validation")
has('ResponsiveHudLayout.computeInteractionModal(layout, {', "feature modal HUD-clear geometry")
has('ResponsiveHudLayout.validateInteractionModal(layout, featureModalLayout)', "feature modal geometry validation")
has('ResponsiveHudLayout.computeCenteredModal(layout, {', "class modal safe-area geometry")
has('ResponsiveHudLayout.validateCenteredModal(layout, classModalLayout)', "class modal geometry validation")
has('ResponsiveHudLayout.computeBottomCenteredCard(layout, {', "vehicle bottom-centered safe geometry")
has('ResponsiveHudLayout.computeSafeFloatingCard(layout, {', "cafe safe-area geometry")
has('ResponsiveHudLayout.validateSafeFloatingCard(layout, cafeCardLayout)', "cafe geometry validation")
has('modal.Name = "ClassActivityModal"', "stable class modal identity")
has('modalScale = Instance.new("UIScale")', "responsive class modal scaling")
has('modalScale.Scale = classModalLayout.scale', "class modal follows validated scale")
has('cafeCardScale = Instance.new("UIScale")', "responsive cafe card scaling")
has('cafeCard.Position = UDim2.fromOffset(cafeCardLayout.x, cafeCardLayout.y)', "cafe card follows validated geometry")
has('shopPanel.Position = UDim2.fromOffset(featureModalLayout.x, featureModalLayout.y)', "shop panel follows HUD-clear geometry")
has('shopPanelScale.Scale = featureModalLayout.scale', "shop panel follows validated scale")
has('travelPanel.Position = UDim2.fromOffset(featureModalLayout.x, featureModalLayout.y)', "travel panel follows HUD-clear geometry")
has('travelPanelScale.Scale = featureModalLayout.scale', "travel panel follows validated scale")
has('vehicleCard.Position = UDim2.fromOffset(vehicleCardLayout.x, vehicleCardLayout.y)', "vehicle card follows validated geometry")
has('vehicleCardScale.Scale = vehicleCardLayout.scale', "vehicle card follows validated scale")
has('cafeCardScale.Scale = cafeCardLayout.scale', "cafe card follows validated scale")
has('card.Position = UDim2.fromOffset(layout.status.x, layout.status.y)', "status placement follows validated geometry")
has('card.Size = UDim2.fromOffset(layout.status.width, layout.status.height)', "status footprint follows normalized geometry")
has('actionRail.Position = UDim2.fromOffset(layout.rail.x, layout.rail.y)', "action rail placement follows validated geometry")
has('quickBar.Position = UDim2.fromOffset(layout.quick.x, layout.quick.y)', "quick bar placement follows validated geometry")
has('return ResponsiveHudLayout.touchExclusionZones(', "client clearance uses tested touch zones")
has('camera:GetPropertyChangedSignal("ViewportSize"):Connect(applyResponsiveHudLayout)', "viewport resize listener")
has('local LEGACY_BLUE = Color3.fromRGB(48, 104, 148)', "shared school palette")
has('cafeCard.Name = "LegacyCafePanel"', "cafe presentation preserved")
has('vehicleCard.Name = "LegacyVehiclePanel"', "vehicle presentation preserved")
has('local function formatLegacyClock(state)', "school clock/day presentation")
has('ContextActionService:BindAction(', "mobile/keyboard vehicle controls preserved")
has('submitAnswer:InvokeServer(', "class interaction preserved")
has('startCafeShift:InvokeServer()', "cafe interaction preserved")
has('spawnVehicle:InvokeServer()', "vehicle interaction preserved")
has('buyHouse:InvokeServer()', "housing server authority preserved")
has('requestTravel:InvokeServer()', "travel server authority preserved")
has('featurePanels:register("shop", {', "shop panel is controller-owned")
has('featurePanels:register("avatar", {', "avatar panel is controller-owned")
has('featurePanels:register("house", {', "house panel is controller-owned")
has('featurePanels:register("travel", {', "travel panel is controller-owned")
has('featurePanels:activate("shop", railInputKind())', "shop activation")
has('featurePanels:activate("avatar", railInputKind())', "avatar activation")
has('featurePanels:activate("house", railInputKind())', "house activation")
has('featurePanels:activate("travel", railInputKind())', "travel activation")
has('featurePanels:close("explicit_close")', "explicit close")
has('featurePanels:close("explicit_back")', "explicit back")
has('featurePanels:restore("travel", "travel_denied")', "travel denial restoration")
has('featurePanels:reset("respawn")', "respawn restoration")
has('travelPanel:SetAttribute("DestinationAuthority", "server-current-room-only")', "travel destination authority boundary")
has('travelLocationsTab.Name = "LocationsTab"', "Travel Locations tab")
has('travelLocationsTab.Text = "Locations"', "Travel Locations label")
has('travelServersTab.Name = "ServersTab"', "Travel Servers tab")
has('travelServersTab.Text = "Servers"', "Travel Servers label")
has('travelServersTab.Active = false', "unverified Servers tab remains inert")
has('headerTail.Name = "HeaderTail"', "angled RHS2 feature-header tail")
has('headerTail.Rotation = 45', "angled RHS2 feature-header geometry")
has('houseHeaderTail.Name = "HouseHeaderTail"', "angled House header tail")
has('houseHeaderTail.Rotation = 45', "angled House header geometry")
has('travelGrid.Name = "TravelDestinationGrid"', "Travel destination-grid hierarchy")
has('placeholder.Text = "UNAVAILABLE"', "unverified Travel cards are explicitly unavailable")
has('shopPanel:SetAttribute("CatalogAuthority", "server-only")', "shop catalog authority boundary")
has('modal.BackgroundColor3 = Rhs2UiStyle.Palette.ShellNavy', "class activity uses RHS2 shell")
has('question.Font = Rhs2UiStyle.Font.Bold', "class activity uses modern title typography")
has('cafeCard.BackgroundColor3 = Rhs2UiStyle.Palette.ShellNavy', "cafe uses RHS2 shell")
has('cafeTitle.Font = Rhs2UiStyle.Font.Bold', "cafe uses modern title typography")
has('vehicleCard.BackgroundColor3 = Rhs2UiStyle.Palette.ShellNavy', "vehicle card uses RHS2 shell")
has('vehicleTitle.Font = Rhs2UiStyle.Font.Bold', "vehicle card uses modern title typography")
has('editorPanel.BackgroundColor3 = Rhs2UiStyle.Palette.ShellNavy', "housing editor uses RHS2 shell")
has('editorTitle.Font = Rhs2UiStyle.Font.Bold', "housing editor uses modern title typography")
lacks('card.BackgroundColor3 = LEGACY_PANEL', "pale primary status surface")
lacks('modal.BackgroundColor3 = LEGACY_PANEL', "pale class activity surface")
lacks('cafeCard.BackgroundColor3 = LEGACY_PANEL', "pale cafe surface")
lacks('vehicleCard.BackgroundColor3 = LEGACY_PANEL', "pale vehicle surface")
lacks('editorPanel.BackgroundColor3 = LEGACY_PANEL', "pale housing editor surface")
lacks('question.Font = Enum.Font.ArialBold', "Arial class activity title")
lacks('cafeTitle.Font = Enum.Font.ArialBold', "Arial cafe title")
lacks('vehicleTitle.Font = Enum.Font.ArialBold', "Arial vehicle title")
lacks('editorTitle.Font = Enum.Font.ArialBold', "Arial housing editor title")
lacks('quickSlot.Font = Enum.Font.ArialBold', "Arial quick-slot typography")
lacks('travelDestination.BackgroundColor3 = LEGACY_BUTTON', "generic pale Travel card")
lacks('{ label = "BAG"', "unverified quick-slot bag semantics")
lacks('{ label = "PHONE"', "unverified quick-slot phone semantics")
lacks('{ label = "ITEMS"', "unverified quick-slot items semantics")
lacks('panel.AnchorPoint = Vector2.new(0.5, 0.5)', "fixed feature-panel center anchor")
lacks('panel.Size = UDim2.new(0.82, 0, 0.76, 0)', "relative feature-panel size")
lacks('panelConstraint.MaxSize = Vector2.new(560, 390)', "feature-panel max-size constraint")
lacks('modal.Position = UDim2.fromScale(0.5, 0.55)', "fixed class modal vertical placement")
lacks('modal.Size = UDim2.new(0.9, 0, 0, 390)', "fixed class modal size")
lacks('vehicleCard.AnchorPoint = Vector2.new(0.5, 1)', "fixed vehicle bottom-center anchor")
lacks('vehicleCard.Position = UDim2.new(0.5, 0, 1, -auxiliaryPanelBottomMargin)', "fixed vehicle bottom placement")
lacks('cafeCard.AnchorPoint = Vector2.new(1, 1)', "fixed cafe anchor")
lacks('cafeCard.Position = UDim2.new(1, -12, 1, -auxiliaryPanelBottomMargin)', "fixed cafe bottom-right placement")
lacks('cafeSizeConstraint.MinSize = Vector2.new(270, 160)', "cafe minimum larger than declared base size")
lacks('card.Position = UDim2.new(0, 12, 1, -bottomMargin)', "large bottom-left status card")
lacks('card.Position = UDim2.new(1, -76, 0, 12)', "fixed desktop status position")
lacks('actionRail.Position = UDim2.new(1, -12, 0, 12)', "fixed desktop rail position")
lacks('quickBar.Position = UDim2.new(0.5, 0, 1, -12)', "fixed desktop quickbar position")
lacks('houseIcon.Parent = gui', "detached house control")

dofile("school/tests/responsive_hud_layout_spec.lua")
dofile("school/tests/avatar_customization_entry_spec.lua")
dofile("school/tests/avatar_customization_runtime_mount_spec.lua")
dofile("school/tests/outfit_operations_spec.lua")
dofile("school/tests/outfit_operations_runtime_spec.lua")
dofile("school/tests/shopping_purchase_authority_spec.lua")
dofile("school/tests/shopping_runtime_authority_spec.lua")
dofile("school/tests/feature_panel_controller_spec.lua")

print("HIGH_SCHOOL_COMPACT_HUD_CONTRACT_PASS")
