--!strict
-- Original, sanitized Grade-2 math activity content.
-- Correct answers and misconception feedback are server-authoritative content.

return {
    {
        id = "g2-math-place-value-001",
        subject = "Math",
        skill = "place-value",
        difficulty = 1,
        prompt = "In 47, what does the 4 mean?",
        choices = { "4 tens", "4 ones", "47 tens" },
        correctIndex = 1,
        hint = "Look at the place where the 4 is written.",
        explanation = "The 4 is in the tens place, so it means 4 tens or 40.",
        misconceptions = {
            [2] = "The 7 is in the ones place, not the 4.",
            [3] = "47 tens would equal 470.",
        },
        provenance = "original-grade2-core-v1",
    },
    {
        id = "g2-math-compare-001",
        subject = "Math",
        skill = "compare-two-digit-numbers",
        difficulty = 1,
        prompt = "Which number is greater?",
        choices = { "65", "58", "They are equal" },
        correctIndex = 1,
        hint = "Compare the tens digits before the ones digits.",
        explanation = "65 is greater because 6 tens is more than 5 tens.",
        misconceptions = {
            [2] = "58 has more ones, but fewer tens.",
            [3] = "The numbers do not have the same value.",
        },
        provenance = "original-grade2-core-v1",
    },
    {
        id = "g2-math-add-100-001",
        subject = "Math",
        skill = "addition-within-100",
        difficulty = 2,
        prompt = "There are 28 red blocks and 15 blue blocks. How many blocks are there altogether?",
        choices = { "43", "33", "53" },
        correctIndex = 1,
        hint = "Add 28 and 15. Regroup the ones if needed.",
        explanation = "28 + 15 = 43.",
        misconceptions = {
            [2] = "33 misses the regrouped ten from the ones.",
            [3] = "53 is ten more than the correct sum.",
        },
        provenance = "original-grade2-core-v1",
    },
    {
        id = "g2-math-subtract-100-001",
        subject = "Math",
        skill = "subtraction-within-100",
        difficulty = 2,
        prompt = "A shelf had 52 books. Students borrowed 19. How many books are left?",
        choices = { "33", "43", "31" },
        correctIndex = 1,
        hint = "Subtract 19 from 52. Regroup if needed.",
        explanation = "52 - 19 = 33.",
        misconceptions = {
            [2] = "43 results from subtracting 9 but not the extra ten.",
            [3] = "31 is two less than the correct difference.",
        },
        provenance = "original-grade2-core-v1",
    },
    {
        id = "g2-math-missing-addend-001",
        subject = "Math",
        skill = "unknown-addend",
        difficulty = 3,
        prompt = "36 + ? = 50. Which number belongs in the box?",
        choices = { "14", "16", "24" },
        correctIndex = 1,
        hint = "Find the difference between 50 and 36.",
        explanation = "14 belongs in the box because 36 + 14 = 50.",
        misconceptions = {
            [2] = "36 + 16 equals 52.",
            [3] = "36 + 24 equals 60.",
        },
        provenance = "original-grade2-core-v1",
    },
    {
        id = "g2-math-measure-001",
        subject = "Math",
        skill = "length-difference",
        difficulty = 2,
        prompt = "A blue ribbon is 12 inches long. A red ribbon is 9 inches long. How much longer is the blue ribbon?",
        choices = { "3 inches", "21 inches", "1 inch" },
        correctIndex = 1,
        hint = "Find the difference between 12 and 9.",
        explanation = "12 - 9 = 3, so the blue ribbon is 3 inches longer.",
        misconceptions = {
            [2] = "21 inches is the total of both lengths, not the difference.",
            [3] = "The difference between 12 and 9 is more than 1.",
        },
        provenance = "original-grade2-core-v1",
    },
    {
        id = "g2-math-equal-groups-001",
        subject = "Math",
        skill = "equal-groups-foundation",
        difficulty = 2,
        prompt = "Four bags each hold 2 apples. How many apples are there in all?",
        choices = { "8", "6", "4" },
        correctIndex = 1,
        hint = "Add 2 once for each of the four bags.",
        explanation = "2 + 2 + 2 + 2 = 8.",
        misconceptions = {
            [2] = "6 counts only three groups of 2.",
            [3] = "4 counts the bags, not all the apples.",
        },
        provenance = "original-grade2-core-v1",
    },
    {
        id = "g2-math-data-001",
        subject = "Math",
        skill = "picture-graph-reasoning",
        difficulty = 3,
        prompt = "A class chart shows 7 students chose apples and 4 chose pears. How many more chose apples?",
        choices = { "3", "11", "4" },
        correctIndex = 1,
        hint = "Find the difference between 7 and 4.",
        explanation = "7 - 4 = 3, so 3 more students chose apples.",
        misconceptions = {
            [2] = "11 is the total number of choices, not how many more.",
            [3] = "4 is the pear count, not the difference.",
        },
        provenance = "original-grade2-core-v1",
    },
}