--!strict
-- Original, sanitized Grade-2 ELA activity content.
-- Correct answers and misconception feedback are server-authoritative content.

return {
    {
        id = "g2-ela-short-vowel-a-001",
        subject = "ELA",
        skill = "short-vowels-cvc",
        difficulty = 1,
        prompt = "Which word has the same short a sound as cat?",
        choices = { "map", "cake", "moon" },
        correctIndex = 1,
        hint = "Say each word slowly and listen to the middle sound.",
        explanation = "Map has the same short a sound as cat.",
        misconceptions = {
            [2] = "Cake uses a long a sound.",
            [3] = "Moon uses a long oo sound.",
        },
        provenance = "original-grade2-core-v1",
    },
    {
        id = "g2-ela-short-vowel-e-001",
        subject = "ELA",
        skill = "short-vowels-cvc",
        difficulty = 1,
        prompt = "Which word belongs with bed and hen because it has the same short e sound?",
        choices = { "pen", "bead", "boat" },
        correctIndex = 1,
        hint = "Listen for the vowel sound in the middle.",
        explanation = "Pen has the same short e sound as bed and hen.",
        misconceptions = {
            [2] = "Bead uses a long e sound.",
            [3] = "Boat uses a long o sound.",
        },
        provenance = "original-grade2-core-v1",
    },
    {
        id = "g2-ela-plural-es-001",
        subject = "ELA",
        skill = "plural-s-es",
        difficulty = 2,
        prompt = "Which sentence uses the correct plural of box?",
        choices = {
            "Two boxes are on the shelf.",
            "Two boxs are on the shelf.",
            "Two box's are on the shelf.",
        },
        correctIndex = 1,
        hint = "Words ending in x usually need two letters added to make the plural.",
        explanation = "Box becomes boxes because nouns ending in x usually add -es.",
        misconceptions = {
            [2] = "Adding only s does not form the regular plural after x.",
            [3] = "An apostrophe does not make this regular noun plural.",
        },
        provenance = "sanitized-schoolwork-skill-evidence",
    },
    {
        id = "g2-ela-spelling-context-001",
        subject = "ELA",
        skill = "spelling-short-vowels",
        difficulty = 2,
        prompt = "The frog sat on a ___. Which word completes the sentence?",
        choices = { "log", "leg", "lug" },
        correctIndex = 1,
        hint = "Choose the word that names something a frog could sit on.",
        explanation = "A log fits the sentence and uses the short o sound.",
        misconceptions = {
            [2] = "Leg is a real word, but it does not fit the sentence meaning.",
            [3] = "Lug is a real word, but it does not name the object in this sentence.",
        },
        provenance = "sanitized-schoolwork-skill-evidence",
    },
    {
        id = "g2-ela-vocab-context-001",
        subject = "ELA",
        skill = "vocabulary-context",
        difficulty = 2,
        prompt = "Maya was eager to open the package. What does eager mean here?",
        choices = { "excited and ready", "too tired to begin", "unable to decide" },
        correctIndex = 1,
        hint = "Use what Maya wants to do next as a clue.",
        explanation = "Eager means excited and ready to do something.",
        misconceptions = {
            [2] = "Too tired is the opposite of being eager to begin.",
            [3] = "The sentence shows strong interest, not uncertainty.",
        },
        provenance = "sanitized-schoolwork-skill-evidence",
    },
    {
        id = "g2-ela-character-feeling-001",
        subject = "ELA",
        skill = "character-feelings",
        difficulty = 2,
        prompt = "Leo practiced all week. He played the song correctly and smiled. How does Leo most likely feel?",
        choices = { "proud", "worried", "angry" },
        correctIndex = 1,
        hint = "Use Leo's practice, success, and smile as clues.",
        explanation = "Leo most likely feels proud because his practice led to success.",
        misconceptions = {
            [2] = "The clues show success, not worry.",
            [3] = "Smiling after succeeding does not suggest anger.",
        },
        provenance = "sanitized-schoolwork-skill-evidence",
    },
    {
        id = "g2-ela-motivation-001",
        subject = "ELA",
        skill = "character-motivation",
        difficulty = 2,
        prompt = "Rain starts falling, so Nina opens her umbrella. Why does she do that?",
        choices = { "to stay dry", "to make the rain louder", "to hide the sidewalk" },
        correctIndex = 1,
        hint = "Think about what an umbrella helps a person do in rain.",
        explanation = "Nina opens the umbrella to stay dry.",
        misconceptions = {
            [2] = "An umbrella is not used to make rain louder.",
            [3] = "The action protects Nina; it is not meant to hide the sidewalk.",
        },
        provenance = "sanitized-schoolwork-skill-evidence",
    },
    {
        id = "g2-ela-setting-001",
        subject = "ELA",
        skill = "setting",
        difficulty = 2,
        prompt = "Ben laces skates, steps onto the ice, and hears a whistle. Where is he most likely?",
        choices = { "an ice rink", "a bedroom", "a garden" },
        correctIndex = 1,
        hint = "Use the skates, ice, and whistle as setting clues.",
        explanation = "Those clues point to an ice rink.",
        misconceptions = {
            [2] = "A bedroom would not normally have skating ice.",
            [3] = "A garden does not match the skating clues.",
        },
        provenance = "sanitized-schoolwork-skill-evidence",
    },
    {
        id = "g2-ela-cause-effect-001",
        subject = "ELA",
        skill = "cause-effect",
        difficulty = 2,
        prompt = "A strong gust pushed Mia's kite into a tree. What caused the kite to get stuck?",
        choices = { "the strong gust", "Mia tying her shoes", "the tree being green" },
        correctIndex = 1,
        hint = "Look for the event that made the kite move.",
        explanation = "The strong gust pushed the kite into the tree.",
        misconceptions = {
            [2] = "Tying shoes does not explain how the kite moved.",
            [3] = "The tree's color did not cause the kite to move.",
        },
        provenance = "sanitized-schoolwork-skill-evidence",
    },
    {
        id = "g2-ela-inference-001",
        subject = "ELA",
        skill = "inference",
        difficulty = 3,
        prompt = "Ava comes inside with wet boots and a dripping umbrella. What can you infer?",
        choices = { "It is raining outside.", "She just baked cookies.", "It is very hot and dry." },
        correctIndex = 1,
        hint = "Combine both wet clues to decide what probably happened outside.",
        explanation = "Wet boots and a dripping umbrella are strong clues that it is raining.",
        misconceptions = {
            [2] = "Nothing in the clues points to baking.",
            [3] = "Wet rain gear does not fit hot, dry weather.",
        },
        provenance = "sanitized-schoolwork-skill-evidence",
    },
    {
        id = "g2-ela-genre-001",
        subject = "ELA",
        skill = "genre",
        difficulty = 2,
        prompt = "A text gives numbered steps for planting a seed. What kind of text is it?",
        choices = { "a how-to text", "a fairy tale", "a poem" },
        correctIndex = 1,
        hint = "Think about a text whose job is to teach steps in order.",
        explanation = "A how-to text explains steps for completing a task.",
        misconceptions = {
            [2] = "A fairy tale tells a story instead of giving real steps.",
            [3] = "A poem is not defined by ordered directions.",
        },
        provenance = "sanitized-schoolwork-skill-evidence",
    },
    {
        id = "g2-ela-main-character-001",
        subject = "ELA",
        skill = "main-character",
        difficulty = 2,
        prompt = "Tara packs her bag, walks to the library, and chooses a book. Her brother waves goodbye. Who is the main character?",
        choices = { "Tara", "her brother", "the librarian" },
        correctIndex = 1,
        hint = "Choose the person whose actions the passage follows most.",
        explanation = "The passage follows Tara's actions, so Tara is the main character.",
        misconceptions = {
            [2] = "The brother appears briefly, but the passage does not follow his actions.",
            [3] = "No librarian takes an action in the passage.",
        },
        provenance = "sanitized-schoolwork-skill-evidence",
    },
}